import { ArrowsOutSimple, CaretLeft, CaretRight, CheckCircle, Crosshair, FileText, Sparkle, Star, UserCircle } from "@phosphor-icons/react";
import { useI18n } from "../../i18n/useI18n.js";

const icons = { caption: FileText, book: Sparkle, target: Crosshair, star: Star };
const ORBIT_CIRCUMFERENCE = 911;

export function NarrationAnalysisBoard({ videos, stages, logs, progress, barGlowPosition, barGlowOpacity, isHolding, animationRefs, selectedIndex, onSelect, onOpen, onScroll, railRef }) {
  const { formatNumber, t } = useI18n();
  return <div className="analysis-layout">
    <section className="analysis-card analysis-card--main" aria-labelledby="analysis-title">
      <h2 id="analysis-title">{t("analysis.title")}</h2>
      <div className="analysis-workflow">{stages.map((stage) => { const Icon = icons[stage.icon]; return <div className={`analysis-stage is-${stage.state}`} key={stage.id}><span className="analysis-stage__icon"><Icon /></span><div><strong>{t(stage.titleKey)}</strong><small>{t(stage.statusKey)}</small></div><span className="analysis-stage__state">{stage.state === "done" ? <CheckCircle weight="fill" /> : <i />}</span></div>; })}</div>
      <div className="analysis-orbit" aria-label={t("analysis.progress", { progress })}><svg viewBox="0 0 320 320" aria-hidden="true"><circle className="analysis-orbit__track" cx="160" cy="160" r="145" /><circle className="analysis-orbit__pulse" ref={animationRefs.pulse} cx="160" cy="160" r="120" /><circle className="analysis-orbit__progress" ref={animationRefs.ring} cx="160" cy="160" r="145" transform="rotate(-90 160 160)" style={{ strokeDasharray: ORBIT_CIRCUMFERENCE, strokeDashoffset: ORBIT_CIRCUMFERENCE - (ORBIT_CIRCUMFERENCE * progress) / 100 }} /></svg><span className="analysis-orbit__halo" ref={animationRefs.halo} aria-hidden="true" /><div className="analysis-orbit__gem" ref={animationRefs.gem}>✦</div><strong>{progress}%</strong></div><p className="analysis-estimate">{t("analysis.estimate")}</p>
      <div className={`analysis-total ${isHolding ? "is-holding" : ""}`}><span>{t("analysis.overall")}</span><div><i ref={animationRefs.bar} style={{ width: `${progress}%` }} /><em className="analysis-total__glow" style={{ left: `${barGlowPosition}%`, opacity: barGlowOpacity }} aria-hidden="true" /></div><b>{progress}%</b>{isHolding && <small>· {t("analysis.holding")}</small>}</div>
    </section>
    <aside className="analysis-aside">
      <section className="analysis-card analysis-materials"><header><h2>{t("analysis.materials.title")}</h2><p>{t("analysis.materials.summary", { count: formatNumber(3) })} <span>{t("analysis.materials.totalDuration")} <strong>08:42</strong></span></p></header><div className="analysis-video-rail" aria-label={t("analysis.materials.list")}><button type="button" aria-label={t("analysis.materials.scrollLeft")} onClick={() => onScroll(-1)}><CaretLeft /></button><div className="analysis-video-scroll" ref={railRef}>{videos.map((video, index) => <button className={`analysis-video ${index === selectedIndex ? "is-selected" : ""}`} key={video.id} type="button" onClick={() => onSelect(index)} aria-pressed={index === selectedIndex}><span className={`analysis-thumb analysis-thumb--${video.scene}`} /><b>{video.label}</b><small>{video.duration}</small>{index === selectedIndex && <span className="analysis-video__expand" role="button" tabIndex="0" aria-label={t("analysis.materials.fullscreen", { episode: video.label })} onClick={(event) => { event.stopPropagation(); onOpen(); }} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); event.stopPropagation(); onOpen(); } }}><ArrowsOutSimple weight="bold" /></span>}</button>)}</div><button type="button" aria-label={t("analysis.materials.scrollRight")} onClick={() => onScroll(1)}><CaretRight /></button></div></section>
      <section className="analysis-card analysis-discover"><h2>{t("analysis.discovered.title")}</h2><div><p><UserCircle /><span>{t("analysis.discovered.characters")}</span><strong>{formatNumber(6)}</strong></p><p><Sparkle /><span>{t("analysis.discovered.turns")}</span><strong>{formatNumber(12)}</strong></p><p><Star /><span>{t("analysis.discovered.highlights")}</span><strong>{formatNumber(18)}</strong></p></div></section>
      <section className="analysis-card analysis-log"><h2>{t("analysis.taskLog")}</h2>{logs.map(({ time, messageKey, state }) => <p className={state === "active" ? "is-active" : ""} key={time}><time>{time}</time><i /> <span>{t(messageKey)}</span>{state === "done" ? <CheckCircle weight="fill" /> : <em />}</p>)}</section>
    </aside>
  </div>;
}
