import { CaretUp, Check, DeviceMobile, Play, Rectangle, Square } from "@phosphor-icons/react";
import { useI18n } from "../../i18n/useI18n.js";

const ratioIcons = { portrait: DeviceMobile, landscape: Rectangle, square: Square };

export function NarrationSettingsForm({ styles, ratios, subtitleStyles, selectedStyle, selectedRatio, selectedSubtitle, requirements, onStyleChange, onRatioChange, onSubtitleChange, onRequirementsChange, onUnavailable }) {
  const { formatNumber, t } = useI18n();
  return <section className="narration-settings" aria-label={t("narration.form.label")}>
    <fieldset className="narration-fieldset narration-style-picker"><legend>{t("narration.form.style")}</legend><div className="narration-style-grid">{styles.map((style) => { const Icon = style.icon; const selected = selectedStyle === style.id; return <button className={`narration-style-card narration-style-card--${style.tone} ${selected ? "is-selected" : ""}`} type="button" aria-pressed={selected} onClick={() => onStyleChange(style.id)} key={style.id}><Icon weight="duotone" aria-hidden="true" />{selected && <span className="narration-selected"><Check weight="bold" /></span>}<strong>{t(style.titleKey)}</strong><small>{t(style.descriptionKey)}</small></button>; })}</div></fieldset>
    <fieldset className="narration-fieldset narration-ratio-picker"><legend>{t("narration.form.ratio")}</legend><div className="narration-ratio-grid">{ratios.map((ratio) => { const Icon = ratioIcons[ratio.glyph]; const selected = selectedRatio === ratio.id; return <button className={`narration-ratio ${selected ? "is-selected" : ""}`} type="button" aria-pressed={selected} onClick={() => onRatioChange(ratio.id)} key={ratio.id}><Icon aria-hidden="true" /><span>{t(ratio.labelKey)}</span>{selected && <i><Check weight="bold" /></i>}</button>; })}</div></fieldset>
    <fieldset className="narration-fieldset narration-voice-picker"><legend>{t("narration.form.voice")}</legend><div className="narration-voice-card"><span className="narration-voice-avatar" aria-hidden="true"><i /><b /></span><div className="narration-voice-main"><strong>{t("narration.form.voiceName")}</strong><span className="narration-wave" aria-hidden="true">▁▂▁▃▅▂▁▆▃▁▂▅▃▁▂▁▅▃▂▆▁</span></div><button type="button" onClick={() => onUnavailable(t("narration.messages.previewingVoice"))}><Play weight="fill" aria-hidden="true" />{t("narration.form.previewVoice")}</button><button type="button" onClick={() => onUnavailable(t("narration.messages.voiceUnavailable"))}>{t("narration.form.changeVoice")}</button></div></fieldset>
    <fieldset className="narration-fieldset narration-subtitle-picker"><legend>{t("narration.form.subtitle")}</legend><div className="narration-subtitle-grid">{subtitleStyles.map((subtitle) => { const selected = selectedSubtitle === subtitle.id; return <button className={`narration-subtitle-card ${subtitle.className} ${selected ? "is-selected" : ""}`} type="button" aria-pressed={selected} onClick={() => onSubtitleChange(subtitle.id)} key={subtitle.id}>{selected && <span className="narration-selected"><Check weight="bold" /></span>}<strong>{t("narration.preview.captionLine1")}<br />{t("narration.preview.captionLine2")}</strong><small>{t(subtitle.labelKey)}</small></button>; })}</div></fieldset>
    <fieldset className="narration-fieldset narration-requirements"><legend>{t("narration.form.moreRequirements")} <CaretUp aria-hidden="true" /></legend><label><span className="sr-only">{t("narration.form.requirements")}</span><textarea maxLength="200" value={requirements} onChange={(event) => onRequirementsChange(event.target.value)} placeholder={t("narration.form.placeholder")} /><em>{formatNumber(requirements.length)} / 200</em></label></fieldset>
  </section>;
}
